### ISSUE TITLE
vega-util and vega-embed

### ISSUE THREAD

**Issue by eytanadar** [altair-viz/altair#2280]
This is one of those... "it worked last week" situations. I'm getting an error on rendering now that I haven't seen in a while when trying to render the chart in jupyter notebook:

`Error loading script: Script error for "vega-util", needed by: vega-embed http://requirejs.org/docs/errors.html#scripterror`

This console is reporting: "`Failed to load resource: the server responded with a status of 404 (Not Found)`" for vega-util.js

I'm perplexed... this is off a conda environment that worked before and a fresh conda environment I installed this morning.  Notebook version 6.1.3, altair version 4.1.0.

I think the relevant node packages installed (globally) are:

```
+ vega-util@1.15.1
+ vega-themes@2.9.0
+ vega@5.15.0
+ canvas@2.6.1
+ vega-cli@5.15.0
+ vega-lite@4.15.0
```

**Comment by Duane321** [comment]
Wow! yea I just got this error this morning as well: #2279

**Comment by eytanadar** [comment]
It looks like there were some changes to the vega-embed repository. Is it possible that some CDN link is down/changed? (cc/ @domoritz )

**Comment by domoritz** [comment]
Yep, I made some "improvements" to the embed build system. Thanks for flagging the issue. I am looking into it!

**Comment by domoritz** [comment]
Please follow https://github.com/vega/vega-embed/issues/557

**Comment by domoritz** [comment]
@eytanadar The map file shown in https://github.com/altair-viz/altair/issues/2280#issuecomment-688989115 is not needed (it's only used for debugging) but it's also there on jsdelivr: 
<img width="794" alt="Screen Shot 2020-09-08 at 10 02 09" src="https://user-images.githubusercontent.com/589034/92506474-62155e00-f1ba-11ea-8283-049b35d3a1c2.png">

**Comment by domoritz** [comment]
So I think this has something to do with the specific deployment. @eytanadar what Altair renderer are you using?

**Comment by domoritz** [comment]
Please try Vega-Embed 6.12.2

**Comment by eytanadar** [comment]
So I flushed all the node packages and reinstalled:

`npm install -g vega vega-themes vega-util vega-cli canvas vega-lite vega-embed@6.12.2`

I now see altair visualizations in jupyter without any specific renderer forced (it's on default according to: `alt.renderers.enable()`)

**Comment by domoritz** [comment]
Awesome. I'm glad that fixed it. Feel free to close the issue.

**Comment by Duane321** [comment]
Hey @eytanadar how did you flush the node packages?

**Comment by domoritz** [comment]
Why do you need to install node packages? I can't think of a scenario in which you need to update node packages to update Altair deps.

**Comment by jakevdp** [comment]
The default renderer will load vega-embed@6 from CDN; no need to change anything locally, except perhaps clearing your browser cache.

If you're using the JupyterLab renderer, it embeds the vega-embed version in the labextension.

**Comment by eytanadar** [comment]
So if it wasn't the node packages, I'm not sure what changed...

I didn't flush my browser cache explicitly.

**Comment by eytanadar** [comment]
Sorry... maybe I get it now... the CDN-hosted vega-embed had a dependency issue. @domoritz fixed it and altair started working again by fetching the right version?

**Comment by domoritz** [comment]
Yep. I don't really know what it was acting up since the previous version was correct (it correctly said that vega-util can be found at the `vega` variable) but I think with requirejs the code was making some assumptions that didn't hold anymore (i.e. it was requesting vega-util from an incorrect location). Either way, it should be working again.

**Comment by eytanadar** [comment]
Got it! Ok, thanks for the fix. My students will be happy later this week when they have to do their homework... :)

@duane321 it sounds like you don't need to do this, but by "flush" I meant that I uninstalled the packages (node uninstall...)

Thanks again @domoritz!

**Comment by domoritz** [comment]
Sorry for breaking everyone's notebooks and thanks for your help with narrowing down the issue.

**Comment by Duane321** [comment]
@domoritz good to know, but yes I am indeed already set :)

**Comment by hathawayj** [comment]
If my issue is still there with VS Code, what can I do fix the break?

**Comment by domoritz** [comment]
@hathawayj which version of embed is being loaded? I suspect forcing a cache refresh fixes it as well.

**Comment by hathawayj** [comment]
@domoritz thanks for the response.  I am trying to figure out the steps to refresh the cache within VS Code.  Or is there a cache refresh command for jupyter?  I am running the interactive python extension - https://code.visualstudio.com/docs/python/jupyter-support-py.  Sorry for my inexperience with this.

**Comment by domoritz** [comment]
Maybe https://stackoverflow.com/questions/39234428/how-do-you-clear-your-visual-studio-code-cache-on-a-mac-linux-machine/42536001?

**Comment by hathawayj** [comment]
Yeah.  Still not working.  Thanks for your quick responses.  I will try to dig into tomorrow morning.

**Comment by hathawayj** [comment]
I think I broke so many things trying to fix this issue that I am not sure what was wrong.  It is working today. Not sure if it was related but I did have to fix my SSL connections.  Thanks for your help.

 https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

**Comment by v5y8** [comment]
running into the same issue @eytanadar has mentioned; cleared google chrome cache as well as "hard reload" via dev console, did not fix issue.

![image](https://user-images.githubusercontent.com/11624344/93275323-74bb0480-f771-11ea-83b7-3f233b528574.png)

**Comment by FedericoCeratto** [comment]
I'm seeing the same error starting today (2023-04-21) with the Python Altair package 4.0.1 in Jupyter Notebook 6.2.0

**Comment by domoritz** [comment]
Oh no. Can you file a new issue in Vega embed with some details and I'll look at it ASAP.

**Comment by domoritz** [comment]
I see an issue at https://observablehq.com/@vega/hello-vega-embed. I'm on it.

**Comment by domoritz** [comment]
I think it's https://github.com/npm/node-semver/issues/554.

**Comment by domoritz** [comment]
Fixed in v6.22.1.

**Comment by FedericoCeratto** [comment]
@domoritz thank you very much!
